import React from 'react';

export const metadata = {

  title: 'Zillion Admin Panel',
  description: 'Generated by Zillion IT Solutions',
}


const Layout = ({ children }) => {


  return (
    <div>
      {children}
    </div>
  );
};

export default Layout;
