import React from 'react'

export const metadata = {

    title: 'Design Plus',
    description: 'Generated by Zillion IT Solutions',
}

const layout = ({ children }) => {
   
    return (
        <div>
            {children}
        </div>
    )
}

export default layout